# Week 11 - Introduction to Modeling, part 2

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold, GridSearchCV, RandomizedSearchCV, LeaveOneOut, RepeatedKFold
from sklearn.metrics import make_scorer

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Import data

from google.colab import files

df = files.upload()

Saving NetworkSecurity_Cleaned.csv to NetworkSecurity_Cleaned.csv


In [3]:
df = pd.read_csv("NetworkSecurity_Cleaned.csv")

pd.set_option('display.max_columns', None)

df.head()

Timestamp Source IP Address Destination IP Address  Source Port  \
0  2023-05-30 06:33:58     103.216.15.12           84.9.164.252        31225   
1  2020-08-26 07:08:30    78.199.217.198         66.191.137.154        17245   
2  2022-11-13 08:23:25      63.79.210.48          198.219.82.17        16811   
3  2023-07-02 10:38:46     163.42.196.10        101.228.192.255        20018   
4  2023-07-16 13:11:07     71.166.185.76        189.243.174.238         6131   

   Destination Port Protocol  Packet Length Packet Type Traffic Type  \
0             17616     ICMP            503        Data         HTTP   
1             48166     ICMP           1174        Data         HTTP   
2             53600      UDP            306     Control         HTTP   
3             32534      UDP            385        Data         HTTP   
4             26646      TCP           1462        Data          DNS   

                                        Payload Data Malware Indicators  \
0  Qui natus odio asperiores nam. Optio nobis ius...       IoC Detected   
1  Aperiam quos modi officiis veritatis rem. Omni...       IoC Detected   
2  Perferendis sapiente vitae soluta. Hic delectu...       IoC Detected   
3  Totam maxime beatae expedita explicabo porro l...       IoC Detected   
4  Odit nesciunt dolorem nisi iste iusto. Animi v...       IoC Detected   

   Anomaly Scores  Alerts/Warnings Attack Type Attack Signature Action Taken  \
0           28.67  Alert Triggered     Malware  Known Pattern B       Logged   
1           51.50  Alert Triggered     Malware  Known Pattern A      Blocked   
2           87.42  Alert Triggered        DDoS  Known Pattern B      Ignored   
3           15.79  Alert Triggered     Malware  Known Pattern B      Blocked   
4            0.52  Alert Triggered        DDoS  Known Pattern B      Blocked   

  Severity Level User Information  \
0            Low    Reyansh Dugal   
1            Low       Sumer Rana   
2            Low     Himmat Karpe   
3         Medium       Fateh Kibe   
4            Low     Dhanush Chad   

                                  Device Information Network Segment  \
0  Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...       Segment A   
1  Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...       Segment B   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...       Segment C   
3  Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...       Segment B   
4  Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...       Segment C   

    Geo-location Data Proxy Information Firewall Logs IDS/IPS Alerts  \
0  Jamshedpur, Sikkim      150.9.97.135      Log Data     Alert Data   
1  Bilaspur, Nagaland    39.123.165.122      Log Data     Alert Data   
2   Bokaro, Rajasthan    114.133.48.179      Log Data     Alert Data   
3  Jaunpur, Rajasthan    39.123.165.122      Log Data     Alert Data   
4  Anantapur, Tripura     149.6.110.119      Log Data     Alert Data   

  Log Source  
0     Server  
1   Firewall  
2   Firewall  
3   Firewall  
4   Firewall

In [4]:
df_copy = df.copy()

cat_var = df_copy[["Traffic Type", "Protocol", "Packet Type", "Attack Type", "Attack Signature", "Action Taken", "Network Segment", "Log Source",
                   ]]

dummy_df = pd.get_dummies(cat_var)

df_copy = df_copy.drop(columns=["Timestamp", "Traffic Type", "Protocol", "Packet Type", "Attack Type", "Attack Signature",
                                "Action Taken", "Network Segment", "Log Source", 'Source IP Address',	'Destination IP Address',
                                'Source Port',	'Destination Port', 'Payload Data', 'Device Information', 'User Information',
                                'Geo-location Data',	'Proxy Information'])

df_enc = pd.concat([df_copy, dummy_df], axis=1)


In [5]:
level = {
    "Low" : 1,
    "Medium" : 2,
    "High" : 3
}

df_enc['Severity Level'] = df_enc['Severity Level'].map(level)
df_enc['Severity Level']

0        1
1        1
2        1
3        2
4        1
        ..
39995    2
39996    3
39997    1
39998    1
39999    2
Name: Severity Level, Length: 40000, dtype: int64

In [6]:
pd.set_option('display.max_columns', None)
df_enc.head()

Packet Length Malware Indicators  Anomaly Scores  Alerts/Warnings  \
0            503       IoC Detected           28.67  Alert Triggered   
1           1174       IoC Detected           51.50  Alert Triggered   
2            306       IoC Detected           87.42  Alert Triggered   
3            385       IoC Detected           15.79  Alert Triggered   
4           1462       IoC Detected            0.52  Alert Triggered   

   Severity Level Firewall Logs IDS/IPS Alerts  Traffic Type_DNS  \
0               1      Log Data     Alert Data             False   
1               1      Log Data     Alert Data             False   
2               1      Log Data     Alert Data             False   
3               2      Log Data     Alert Data             False   
4               1      Log Data     Alert Data              True   

   Traffic Type_FTP  Traffic Type_HTTP  Protocol_ICMP  Protocol_TCP  \
0             False               True           True         False   
1             False               True           True         False   
2             False               True          False         False   
3             False               True          False         False   
4             False              False          False          True   

   Protocol_UDP  Packet Type_Control  Packet Type_Data  Attack Type_DDoS  \
0         False                False              True             False   
1         False                False              True             False   
2          True                 True             False              True   
3          True                False              True             False   
4         False                False              True              True   

   Attack Type_Intrusion  Attack Type_Malware  \
0                  False                 True   
1                  False                 True   
2                  False                False   
3                  False                 True   
4                  False                False   

   Attack Signature_Known Pattern A  Attack Signature_Known Pattern B  \
0                             False                              True   
1                              True                             False   
2                             False                              True   
3                             False                              True   
4                             False                              True   

   Action Taken_Blocked  Action Taken_Ignored  Action Taken_Logged  \
0                 False                 False                 True   
1                  True                 False                False   
2                 False                  True                False   
3                  True                 False                False   
4                  True                 False                False   

   Network Segment_Segment A  Network Segment_Segment B  \
0                       True                      False   
1                      False                       True   
2                      False                      False   
3                      False                       True   
4                      False                      False   

   Network Segment_Segment C  Log Source_Firewall  Log Source_Server  
0                      False                False               True  
1                      False                 True              False  
2                       True                 True              False  
3                      False                 True              False  
4                       True                 True              False

In [7]:
# Logistic Regression

# Use important features only captured from PCA (HW 9.2)
X = df_enc[["Packet Length", 'Anomaly Scores', 'Traffic Type_DNS', 'Traffic Type_FTP',
       'Traffic Type_HTTP', 'Protocol_ICMP', 'Protocol_TCP', 'Protocol_UDP', 'Packet Type_Control', 'Packet Type_Data',
            'Network Segment_Segment A', 'Network Segment_Segment B', 'Network Segment_Segment C', 'Log Source_Firewall', 'Log Source_Server']]

y = df_enc['Severity Level']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42,test_size=0.2)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_LR = LogisticRegression(max_iter=2000)

model_LR.fit(X_train_scaled, y_train)

y_pred = model_LR.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.333625

Classification Report:
               precision    recall  f1-score   support

           1       0.33      0.23      0.27      2673
           2       0.35      0.35      0.35      2729
           3       0.32      0.42      0.37      2598

    accuracy                           0.33      8000
   macro avg       0.33      0.33      0.33      8000
weighted avg       0.33      0.33      0.33      8000


Confusion Matrix:
 [[ 603  917 1153]
 [ 618  967 1144]
 [ 624  875 1099]]


In [8]:
# Random Forest Classifier

param_grid = {
    'n_estimators' : [10,25,40],
    'max_depth' : [15, 20, 25],
    'max_features' : [0.8, 0.9],
    'bootstrap' : [True]
}

model_RFC = RandomForestClassifier(random_state=42)

randsearchcv = RandomizedSearchCV(model_RFC, cv=5, random_state=42, param_distributions=param_grid, n_iter=5, n_jobs=-1)

randsearchcv.fit(X_train_scaled, y_train)

print("Best Parameters:", randsearchcv.best_params_)
print("Best Cross-Val Score:", randsearchcv.best_score_)

# Best Parameters: {'n_estimators': 100, 'max_features': 0.9, 'max_depth': 20, 'bootstrap': True}
# Best Cross-Val Score: 0.33971875
# Not a good model as accuracy is only 33%

Best Parameters: {'n_estimators': 10, 'max_features': 0.8, 'max_depth': 15, 'bootstrap': True}
Best Cross-Val Score: 0.33971875


In [9]:
param_grid2 = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [10, 20, 30, None],
    'max_features': ['sqrt', 0.5, 0.8, 1.0],
    'bootstrap': [True]
}

model_rfr2 = RandomForestRegressor(random_state=42)

cv = RepeatedKFold(n_splits=5, n_repeats=3, random_state=42)

rand_search = RandomizedSearchCV(
    estimator=model_rfr2,
    param_distributions=param_grid2,
    n_iter=5,
    scoring='neg_mean_squared_error',
    cv=cv,
    n_jobs=-1,
    random_state=42
)

rand_search.fit(X_train, y_train)

best_model = rand_search.best_estimator_
rmse = np.sqrt(-rand_search.best_score_)

print("Best Parameters:", rand_search.best_params_)
print("Best RMSE:", rmse)

# Best Parameters: {'n_estimators': 100, 'max_features': 0.5, 'max_depth': 10, 'bootstrap': True}
# Best RMSE: 0.8170150582361623
# This is not a good model either because the 'y range' of this model is 1-3. So each prediction if off by 0.82 units, and that is a large margin.

Best Parameters: {'n_estimators': 100, 'max_features': 0.5, 'max_depth': 10, 'bootstrap': True}
Best RMSE: 0.8170150582361623
